### ISSUE TITLE
Catch error when unwraping peer_addr() from stream

### ISSUE THREAD

**Issue by samuel-rufi** [Alex6323/netzwerk#7]
Documentation doesn't state when an error gets thrown in `stream.peer_addr()`. Anyways, we need to check the value before unwraping it. See `tcp/mod.rs`

```
async fn recv(&mut self) -> result::MessageResult<Event> {
        let mut buffer = vec![0; MAX_BUFFER_SIZE];

        let num_bytes = self.stream.read(&mut buffer)
            .await
            .expect("error receiving bytes using TCP");

        Ok(Event::MessageReceived {
            num_bytes,
            sender_addr: Address::new(self.stream.peer_addr().unwrap()),
            bytes: buffer
        }.into())
    }
```

**Comment by Alex6323** [comment]
Yes, you're right. This issue can be closed as this was solved during a refactoring. I only do unwrapping during initial prototyping to get something going real quick. Unwraps are only acceptable in rare cases, where it is ensured due to some other logic, that it can't fail. Correct error handling across the whole lib is in progress ;)
